app:
  auth:
    jwt-secret-key: vIy3Wg073BAzHR4aWdhJQt8HYrLCqXsGLf8r7NcimRJYHDY4NqyCXoWsNFJCnn3
    session-duration: P30D
  scripts-folder: C:\Users\6rayWa1cher\Desktop\scripts
  exec-script:
    buffer-size: 1048576
    max-output-size: 1048576
    environments:
      - name: python
        exec: "python {1}"
        sourceFilename: "{1}.py"
      - name: java12
        #        compile:
        #          - "copy \"{1}\" \"{3}/Main.java\""
        #          - "javac -d {3} {3}/Main.java"
        exec: "java {1}"
        sourceFilename: "{1}.java"