spring.profiles.active: dev

app:
  auth:
    jwt-secret-key: vIy3Wg073BAzHR4aWdhJQt8HYrLCqXsGLf8r7NcimRJYHDY4NqyCXoWsNFJCnn3
    access-token-duration: P1D
    refresh-token-duration: P90D
  scripts-folder: C:\Users\6rayWa1cher\Desktop\scripts
  exec-script:
    buffer-size: 1048576
    max-output-size: 1048576
    environments:
      - name: python
        exec: "python {1}"
        sourceFilename: "{1}.py"
      - name: java12
        exec: "java {1}"
        sourceFilename: "{1}.java"
# ===============================
# REQUEST MAX SIZE
# ===============================
spring.servlet.multipart.maxFileSize: 1572864
spring.servlet.multipart.maxRequestSize: 1572864
server.tomcat.max-http-post-size: 1572864
# ===============================
# DB CONNECTION
# ===============================
spring.datasource.url: jdbc:postgresql://localhost:5433/postgres
spring.datasource.username: postgres
spring.datasource.password: postgres
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.default_schema: public
spring.jpa.properties.hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
# ===============================
# SPRING ACTUATOR
# ===============================
management.endpoints.web.exposure.include: "*"